### PR TITLE
issue-55-56

### LINKED ISSUE #55: After editing the order status, the orders get disappear.
**Describe the bug**
The client is having an issue when the custom order status is edited, then that particular order is getting disappeared from the orders page as well as the custom status disappears.

**To Reproduce**
1) Create a custom order status.
2) Place an order.
3) Change the status to that custom order status.
4) Edit that custom status.
5) You will not find that order with that particular custom status. 

**Expected behavior**
The order should not disappear when we edit the custom status.

**Additional context**
The issue is been replicated to the client with the last update of the plugin. 

Link: https://wordpress.org/support/topic/after-editing-order-status-disappeard-orders/

### LINKED ISSUE #56: When we change the slug of the custom order status, orders having that custom status will not be seen on Orders page
**Describe the bug**
When we change the slug of the COS, then the orders which have that custom status will not be seen on the Orders page. Though they are present in the database but will not be seen on the Orders page.

**To Reproduce**
1. Create one custom order status, like this: https://prnt.sc/10c0t8t
2. After creating the COS, change 1 order status to that newly created COS. like this: https://prnt.sc/10c0u0e
3. Then, change the slug of the COS and update it. like this: https://prnt.sc/10c0wnx
4. Then go to the orders page, where the order in which the status is changed to that COS will not be seen. like this: https://prnt.sc/10c0y0o

**Expected behavior**
No orders should get disappear from the orders page. For this, we should not allow changing the slug of the custom order status.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/26336

### PR DESCRIPTION
**Pull request by Shasvat7**
When we edit the slug in cos, orders were getting removed from the orders page for that cos. So now in this commit, it is fixed as the slug is not editable after it is saved.

Fixes #55

Fixes #56

### CODE REVIEW

File: includes/class-alg-wc-custom-post-type-for-order-statuses.php [hunk 1]
```diff
@@ -328,12 +328,17 @@ public function alg_register_meta_boxes() {
 		 * @author  Tyche Softwares
 		 */
 		public function alg_my_display_callback( $post ) {
+			if ( '' !== get_post_meta( $post->ID, 'status_slug', true ) ) {
+				$readonly = 'readonly';
```
Comment (ashokrane) [inline includes/class-alg-wc-custom-post-type-for-order-statuses.php:332]: Change this variable `$readonly` to `$slug_readonly`.

**Review by ashokrane — APPROVED** [review]
